[package]
name = "boids-rs"
version = "0.1.0"
edition = "2024"
authors = ["Dyson Dyson <dyson.dyson@icloud.com>"]
repository = "https://github.com/DoctorDalek1963/boids-rs"
license = "GPL-3.0-only"
publish = false

[dependencies]
